### ISSUE TITLE
where is the location of the model download ?

### ISSUE THREAD

**Issue by kaiyes** [mzbac/flux.swift.cli#1]
I downloaded the prebuilt binary.

When I ran it for the first time, normally its downloading the schenell model.

So where is it being downloaded ?

also, is there a local ram/graphics requirement ? Or that doesn't matter since its quantised ?

<img width="921" alt="Screenshot 2024-10-16 at 6 23 40 PM" src="https://github.com/user-attachments/assets/d14bdba1-e9ec-4840-a536-0727a6b9e577">

**Comment by mzbac** [comment]
The model currently downloads to the user's Documents folder because it uses the default download base (https://github.com/huggingface/swift-transformers/blob/main/Sources/Hub/HubApi.swift#L24). Regarding RAM requirements, even with quantization enabled, it will still require around 15GB of memory. Running on a machine with less than that may cause swapping, which will significantly slow down generation.
